name = "worker-email"
type = "webpack"

account_id = "............................"
workers_dev = true
route = "/"
zone_id = ""
compatibility_date = "2021-11-08"

[vars]
MAILGUN_KEY = "........................................."
MAILGUN_DOMAIN = "sandbox...................mailgun.org"
ADMIN_EMAIL = "adminemail"
ALLOWED_ORIGIN = "yourdomain.xyz"
LOGO_URL = "xyz.com/assets/logo.png" 
FROM = "ABCD <noreply@abc.xyz>"