name = "worker-email"
main = "src/index.js"
compatibility_date = "2022-11-09"

workers_dev = true

[vars]
MAILGUN_KEY = "........................................................"
MAILGUN_DOMAIN = "sandbox...................................mailgun.org"
ADMIN_EMAIL = "info@abc.com"
ALLOWED_ORIGIN = "https://www.abc.com"
LOGO_URL = "xyz.com/assets/logo.png" 
FROM = "ABC <noreply@abc.com>"